version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      codebuild-breakpoint

      #- for GOOS in linux darwin windows; do go build -v ./lab_01/hello.go; mkdir -p lab_01/out/$GOOS; mv hello* lab_01/out/$GOOS/; done
      #- sh test.sh
      #- echo $CODEBUILD_BUILD_ARN | cut -d ':' -f5
      #- cat $CODEBUILD_BUILD_ARN | cut -d ':' -f5
      #- echo $CODEBUILD_BUILD_ID
      #- echo $build_ssh_key
#artifacts:
#  files:
#    - lab_01/**/*
#
